### ISSUE TITLE
Quickstart prerequisites 

### ISSUE THREAD

**Issue by maacl** [narkisr-deprecated/gelfino#1]
Gelfino looks like a great project!

What are the prerequisites for running the Quickstart example (https://github.com/narkisr/gelfino/wiki/quickstart) ?

Just a redis server or?

**Comment by narkisr** [comment]
I added a readme to the example, try to follow that and ask whatever is unclear to you.

Best regards
Ronen

**Comment by maacl** [comment]
Thanks - got as far as lein install, which blows up with:

Compiling gelfino.storm
Exception in thread "main" java.lang.ClassNotFoundException: backtype.storm.StormSubmitter, compiling:(storm.clj:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3387)
    at clojure.lang.Compiler.compile1(Compiler.java:7035)
    at clojure.lang.Compiler.compile1(Compiler.java:7025)
    at clojure.lang.Compiler.compile(Compiler.java:7097)
    at clojure.lang.RT.compile(RT.java:387)
    at clojure.lang.RT.load(RT.java:427)
    at clojure.lang.RT.load(RT.java:400)
    at clojure.core$load$fn__4890.invoke(core.clj:5415)
    at clojure.core$load.doInvoke(core.clj:5414)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5227)
    at clojure.core$compile$fn__4895.invoke(core.clj:5426)
    at clojure.core$compile.invoke(core.clj:5425)
    at user$eval7.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: backtype.storm.StormSubmitter
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at gelfino.storm$loading__4784__auto__.invoke(storm.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3382)
    ... 26 more
Compilation failed.

**Comment by maacl** [comment]
Above can be fixed by adding  [storm "0.8.1"] as a dependency.

Now I get to foreman start in the example which stops with:

08:00:43 fnord.1   | started with pid 13530
08:00:43 gelfino.1 | started with pid 13531
08:00:43 gelfino.1 | Exception in thread "main" java.lang.NoClassDefFoundError: gelfino/example/core
08:00:43 gelfino.1 | Caused by: java.lang.ClassNotFoundException: gelfino.example.core
08:00:43 gelfino.1 |    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
08:00:43 gelfino.1 |    at java.security.AccessController.doPrivileged(Native Method)
08:00:43 gelfino.1 |    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
08:00:43 gelfino.1 |    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
08:00:43 gelfino.1 |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
08:00:43 gelfino.1 |    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
08:00:43 gelfino.1 | exited with code 1
08:00:43 system    | sending SIGTERM to all processes
SIGTERM received
08:00:43 fnord.1   | terminated by SIGTERM

lein compile in /example produces:

Compiling gelfino.example.core
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(core.clj:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3342)
    at clojure.lang.Compiler.compile1(Compiler.java:6985)
    at clojure.lang.Compiler.compile1(Compiler.java:6975)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$compile$fn__4615.invoke(core.clj:5397)
    at clojure.core$compile.invoke(core.clj:5396)
    at user$eval7.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at clojure.lang.RT.loadClassForName(RT.java:2030)
    at clojure.lang.RT.load(RT.java:417)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:604)
    at clojure.core$use.doInvoke(core.clj:5363)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at cheshire.core$loading__4784__auto__.invoke(core.clj:1)
    at cheshire.core__init.load(Unknown Source)
    at cheshire.core__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at clojure.lang.RT.loadClassForName(RT.java:2030)
    at clojure.lang.RT.load(RT.java:417)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$require.doInvoke(core.clj:5352)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at gelfino.example.core$loading__4505__auto__.invoke(core.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3337)
    ... 26 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at cheshire.factory__init.__init0(Unknown Source)
    at cheshire.factory__init.<clinit>(Unknown Source)
    ... 67 more
Compilation failed.

**Comment by narkisr** [comment]
Please make sure that your using lein-2 preview 10, as storm was already in the deps under:

``` clojure
:profiles {:dev  
             {:dependencies 
              [[lein-clojars "0.6.0"]  
               [org.codehaus.groovy/groovy "1.7.8"]
               [storm "0.8.1"]
               [cljs-uuid "0.0.2"]
               [com.narkisr/java.data "0.0.1-SNAPSHOT"]
               [org.clojars.tavisrudd/redis-clojure "1.3.1-SNAPSHOT"]]}}
```

You don't need to add it, also iv cleared this ns from aot compilation (as it wasn't necessery) and updated the readme to include lein2.

Regarding the second issue iv added gelfino.example.core to the example/project.clj AOT, 

Upgrade to lein2-preview 10 iv you already havent

``` bash
$ lein version 
Leiningen 2.0.0-preview10 on Java 1.6.0_26 Java HotSpot(TM) 64-Bit Server VM
```

Start with a clean .m2 local repo and pull the latest changes:

``` bash
$ mv ~/.m2 ~/.m2-bac
$ git pull origin master
$ lein clean 
$ cd example 
$ lein clean
```

Thanks for reporting
Ronen

**Comment by maacl** [comment]
Thanks. This got me to foreman start resulting in:

14:56:35 fnord.1   | started with pid 17940
14:56:35 gelfino.1 | started with pid 17941
14:56:36 fnord.1   |
/Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric/gems/eventmachine-1.0.0/lib/rubyeventmachine.bundle:
[BUG] Segmentation fault
14:56:36 fnord.1   | ruby 1.9.2p320 (2012-04-20 revision 35421)
[x86_64-darwin11.4.0]
14:56:36 fnord.1   | -- control frame ----------
14:56:36 fnord.1   | c:0011 p:-17563573843568 s:0028 b:0028 l:000027
d:000027 TOP
14:56:36 fnord.1   | c:0010 p:---- s:0026 b:0026 l:000025 d:000025 CFUNC
 :require
14:56:36 fnord.1   | c:0009 p:0095 s:0022 b:0022 l:000021 d:000021 TOP
 /Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric
/gems/eventmachine-1.0.0/lib/eventmachine.rb:8
14:56:36 fnord.1   | c:0008 p:---- s:0020 b:0020 l:000019 d:000019 FINISH
14:56:36 fnord.1   | c:0007 p:---- s:0018 b:0018 l:000017 d:000017 CFUNC
 :require
14:56:36 fnord.1   | c:0006 p:0011 s:0014 b:0014 l:000013 d:000013 TOP
 /Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric
/gems/fnordmetric-1.0.0/lib/fnordmetric.rb:1
14:56:36 fnord.1   | c:0005 p:---- s:0012 b:0012 l:000011 d:000011 FINISH
14:56:36 fnord.1   | c:0004 p:---- s:0010 b:0010 l:000009 d:000009 CFUNC
 :require
14:56:36 fnord.1   | c:0003 p:0011 s:0006 b:0006 l:0012d8 d:001878 EVAL
metrics.rb:1
14:56:36 fnord.1   | c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
14:56:36 fnord.1   | c:0001 p:0000 s:0002 b:0002 l:0012d8 d:0012d8 TOP
14:56:36 fnord.1   | ---------------------------

## 14:56:36 fnord.1   | -- Ruby level backtrace information

14:56:36 fnord.1   | metrics.rb:1:in `<main>'
14:56:36 fnord.1   | metrics.rb:1:in`require'
14:56:36 fnord.1   |
/Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric/gems/fnordmetric-1.0.0/lib/fnordmetric.rb:1:in
`<top (required)>'
14:56:36 fnord.1   |
/Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric/gems/fnordmetric-1.0.0/lib/fnordmetric.rb:1:in
`require'
14:56:36 fnord.1   |
/Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric/gems/eventmachine-1.0.0/lib/eventmachine.rb:8:in
`<top (required)>'
14:56:36 fnord.1   |
/Users/mac/.rvm/gems/ruby-1.9.2-p320@fnordmetric/gems/eventmachine-1.0.0/lib/eventmachine.rb:8:in
`require'

## 14:56:36 fnord.1   | -- C level backtrace information

14:56:36 fnord.1   | [NOTE]
14:56:36 fnord.1   | You may have encountered a bug in the Ruby interpreter
or extension libraries.
14:56:36 fnord.1   | Bug reports are welcome.
14:56:36 fnord.1   | For details: http://www.ruby-lang.org/bugreport.html
14:56:37 fnord.1   | terminated by SIGABRT
14:56:37 system    | sending SIGTERM to all processes
SIGTERM received

/mac

**Comment by narkisr** [comment]
Ok it looks like https://github.com/eventmachine/eventmachine/issues/265

It does not reproduce on my machine but Iv tried to lock the evnetmachine version to 1.0.0 can you pull and see if it helps?

``` bash
$ git pull origin master
$ bundle install
```

Thanks
Ronen

**Comment by maacl** [comment]
Same output for eventmachine1.0.0.

**Comment by narkisr** [comment]
Ok iv opened a question on fnordmetric mailing list, https://groups.google.com/forum/?fromgroups=#!topic/fnordmetric/U7NoIMaDiNI

Looking at the project travis.yaml I see that they use 1.9.3, iv pushed an updated that uses the latest 1.9.3, iv also cleared out vagrant that caused issues with ffi.

Please try:

``` bash
$ rvm install ruby-1.9.3-rc1
$ cd example 
$ bundle install 
```

I hope it will end this saga :), let me know if it worked

Thanks
Ronen

**Comment by maacl** [comment]
Thanks, will give that a shot later this evening. Meanwhile got it working
just fine on Ubuntu (OSX Lion is my primary dev env).

/mac

**Comment by narkisr** [comment]
Great! 

Im planning to add couple of new features including storm integration so I didn't keep the example code up to track, 

Let me know if you got it going to the Mac

Thanks
Ronen

**Comment by maacl** [comment]
Happy to report also now working on OSX. Embarrassingly I think my issues might have been related to me not understanding the whole rvm/Ruby/gems thing well enough.

**Comment by narkisr** [comment]
Cool, Im happy that its working now, feel free to contact me if you have further questions 

Ronen
